"""M2-01 fix uniqueness constraint and trait_type check

Revision ID: 215d7de0a40f
Revises: a42b70029408
Create Date: 2026-04-05 01:25:27.682814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215d7de0a40f'
down_revision = 'a42b70029408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_identity_template_user_artwork', ['user_id', 'artwork_id'])

    with op.batch_alter_table('identity_traits', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_traits', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('identity_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_identity_template_user_artwork', type_='unique')

    # ### end Alembic commands ###
