"""M2-01 add indexes on foreign keys

Revision ID: cdbed24901bd
Revises: 215d7de0a40f
Create Date: 2026-04-05 01:28:55.166255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbed24901bd'
down_revision = '215d7de0a40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_templates_artwork_id'), ['artwork_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('identity_traits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_traits_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_traits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_traits_template_id'))

    with op.batch_alter_table('identity_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_identity_templates_artwork_id'))

    # ### end Alembic commands ###
